### ISSUE TITLE
Sorting of recent documents

### ISSUE THREAD

**Issue by tomas-52** [mate-desktop/mate-menus#100]
#### Expected behaviour
They should be sorted by the time they were last opened (modified in recently-used.xbel)

#### Actual behaviour
Sorted by added in recently-used.xbel

#### Steps to reproduce the behaviour
Let us say that you set the number of recent documents for advanced mate menu to 5,
then open documents named "1" to "6" in the following order: 1, 2, 3, 4, 5, 1, 6.
In recent documents you will see 6, 5, 4, 3 and 2 instead of 6, 1, 5, 4 and 3.

#### MATE general version
1.26

#### Package version
20.04.3

#### Linux Distribution
Mint

**Comment by tomas-52** [comment]
https://github.com/linuxmint/mint20.2-beta/issues/10

**Comment by tomas-52** [comment]
https://github.com/linuxmint/mint20.2-beta/issues/64
https://github.com/linuxmint/mint20.2-beta/issues/75

For mintmenu 1.6.4 in Linux Mint 20.2 the problem was solved (not so for mate-menu).

**Comment by mbkma** [comment]
> (not so for mate-menu).

Which menu do you mean especially? If you mean the advanced menu used by Ubuntu MATE than you should open a bugreport there https://github.com/ubuntu-mate/mate-menu.

**Comment by raveit65** [comment]
Wrong repo, mate-menu is ubuntu-mate (search at github) production.
