### ISSUE TITLE
New Collection menu should be configurable

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-menus#101]
#### Expected behaviour
Mozo, dconf or gsettings should allow user to disable or enable Collection menu.

#### Actual behaviour
New Collection menu seems to be hard-coded. Mozo, dconf or gsettings know nothing about it.

#### Steps to reproduce the behaviour
Install Ubuntu MATE 21.10 daily

#### MATE general version
1.24.1

#### Package version
1.26.0-0ubuntu1

#### Linux Distribution
Ubuntu MATE 21.10

#### Link to bugreport of your Distribution (requirement)
https://pad.lv/1941942

**Comment by N0rbert** [comment]
Maybe related with https://github.com/mate-desktop/mozo/issues/74

**Comment by N0rbert** [comment]
Programmatic way to disable was first introduced in [this comment](https://github.com/mate-desktop/mate-menus/pull/86#issuecomment-903735523), may be adapted to the following:

```
mkdir -p /home/$USER/.local/share/desktop-directories/
cat <<EOF > /home/$USER/.local/share/desktop-directories/mate-collection.directory
[Desktop Entry]
Name=Collection
Comment=The most frequently used shortcuts
Icon=starred
Type=Directory
NoDisplay=true
EOF
```
then reboot.

But it is not user-friendly and not expected at all.

**Comment by mbkma** [comment]
See https://github.com/mate-desktop/mozo/pull/82
