### ISSUE TITLE
Wine applications not being added to Wine sub-menu

### ISSUE THREAD

**Issue by jelabarre59** [mate-desktop/mate-menus#2]
Under the old Gnome2 system, as well as various other desktops, whenever an application was installed through Wine, it would be added to it's appropriate sub-menu under the Wine menu entry in the Gnome menu.  Something has changed in the Mate fork of this, since now _nothing_ is getting added.  To even get the Wine menu at all I had to edit /etc/xdg/menus/mate-applications.menu to add the "MergeDir" section.  But even after doing that, subsequent Wine application installs are not creating the appropriate sub-menus.

As an example: once you have made the modification in /etc/xdg/menus/mate-applications.menu to see the Wine menu, try installing IrfanView (a quick and non-intrusive install to try) using Winetricks with the command "winetricks irfanview", which will run the appropriate steps needed.  (you may want to grab the latest development build at https://code.google.com/p/winetricks/source/checkout ).  Once you've run this, it will create the desktop entries (if you have checked the options to do so), will put "IrfavView - Thumbnails" in the "Other" menu, but does not create the IrfanView submenu under the Wine menu, and does not create an entry for IrfanView _anyplace_ in the menus.

Expected behavior is that it should create sub-menus under the Wine menu (as had happened under other desktop shells/environments), or add it directly to the Wine menu if the application in question would create it's icon as a top-level item.

**Comment by rezso** [comment]
@NiceandGently: the best way (imho) if we add the Cinnamon's setup_merge_dir_symlink() fuction to matemenu-tree.c file, and call this function in  resolve_default_merge_dirs().

**Comment by joakim-tjernlund** [comment]
Is this still a problem?

**Comment by raveit65** [comment]
> @NiceandGently: the best way (imho) if we add the Cinnamon's setup_merge_dir_symlink() fuction to matemenu-tree.c file, and call this function in  resolve_default_merge_dirs().

@rezso 
Any chance of a pull request for this?

**Comment by rezso** [comment]
@raveit65 
Yes, but the code is untested, I haven't any merged menu.

**Comment by rezso** [comment]
@raveit65 
https://github.com/mate-desktop/mate-menus/pull/55

**Comment by raveit65** [comment]
Anyone around here who use *wine* and can test if this PR works?
Maybe on gentoo?
@joakim-tjernlund

**Comment by joakim-tjernlund** [comment]
Mail me a patch for MATE 1.18 and I will test it

**Comment by raveit65** [comment]
mail ????, simply add .patch to PR link in browsers :-)
https://patch-diff.githubusercontent.com/raw/mate-desktop/mate-menus/pull/55.patch

**Comment by joakim-tjernlund** [comment]
Ahh, how I have looked for that, why do they not have a button for that :(
Can you do something similar on any commit already in the repo?

**Comment by raveit65** [comment]
yes, it works on all commits on github
.diff or .patch

**Comment by joakim-tjernlund** [comment]
Good :)

Anyhow, patch installed and after logout/login I see:
```
cd ~.config/menus/
ls -ld *merged
drwx------ 2 jocke users 41 Jun 20 11:56 applications-merged/
lrwxrwxrwx 1 jocke users 45 Aug 16 17:38 mate-applications-merged -> /home/jocke/.config/menus/applications-merged/
```
So it works although I would have expect a relative symlink

**Comment by joakim-tjernlund** [comment]
Could we have this in 1.18 too?
Also, it would be nice if you could look out MATE 1.18 branches and release accumulated
commits

**Comment by raveit65** [comment]
I did already relese atril-1.18.1 yesterday.
And yes, i will push that to 1.18 branch +  an new point release for mate-menus.
And wine menu entries are there?

**Comment by joakim-tjernlund** [comment]
I wonder, should MATE run xdg-user-dirs-update automatically too?

**Comment by joakim-tjernlund** [comment]
I don't you Wine, sorry. I just stumbled over a Gentoo bug that pointed to this
bug so I wanted to know if this was fixed.

**Comment by raveit65** [comment]
I have this in autostart here
```
[rave@mother ~]$ cat /home/rave/.config/autostart/user-dirs-update-gtk.desktop 
[Desktop Entry]
Encoding=UTF-8
Exec=xdg-user-dirs-gtk-update
Name=User folders update
```
Install by
```
[root@mother rave]# dnf provides /etc/xdg/autostart/user-dirs-update-gtk.desktop
Letzte Prüfung auf abgelaufene Metadaten: vor 0:04:06 am Mi 16 Aug 2017 17:53:07 CEST.
xdg-user-dirs-gtk-0.10-10.fc26.x86_64 : Gnome integration of special directories
Quelle      : @System

```

**Comment by joakim-tjernlund** [comment]
That is xdg-user-dirs-gtk-update, not xdg-user-dirs-update, which I think is different

Gentoo has some funky xinitrc.d file:
```
cat 10-user-dirs-update-mate
#!/bin/sh

# Create various XDG directories, and write ~/.config/user-dirs.dirs, etc.
# That file is read by glib to get XDG_PICTURES_DIR, etc

if [ "$DESKTOP_SESSION" = "mate" ]; then
	if type xdg-user-dirs-update >/dev/null 2>&1; then
		xdg-user-dirs-update
	fi
fi
```
I wonder if that should be inside MATE instead.

BTW, would be great if you could release a new mate-themes too, I want to see
if yelp scroll fix will help Evolution too, the horizontal scrollbar if not drawn there either.

**Comment by rezso** [comment]
@raveit65 
what do you think, this condition is needed?
https://github.com/rezso/mate-menus/commit/16f58f797ddeebb0c5a1f701034b8838a927cea2

**Comment by raveit65** [comment]
Let's hear what package maintainer thinks?
@XRevan86 
Can you handle this PR please?

**Comment by rezso** [comment]
Okay, after installing Zuma's revenge with wine:

rezso@papi:~/.config$ ls -1 -R ~/.config/menus
/home/rezso/.config/menus:
applications-merged
mate-applications-merged

/home/rezso/.config/menus/applications-merged:
'wine-Programs-PopCap Games-Zuma'\''s Revenge!-Play Zuma'\''s Revenge!.menu'
'wine-Programs-PopCap Games-Zuma'\''s Revenge!-Uninstall Zuma'\''s Revenge!.menu'
'wine-Programs-PopCap Games-Zuma'\''s Revenge!-View Readme.menu'
'wine-Programs-PopCap Games-Zuma'\''s Revenge!-Visit PopCap.com.menu'
xdg-desktop-menu-dummy.menu

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-menus/commit/923a0d96b4de690e48e1ebd2efe9ff544cc7b254
