### ISSUE TITLE
System becomes unresponsive after first time opening the menu

### ISSUE THREAD

**Issue by AndyProk** [mate-desktop/mate-menus#22]
Every time after booting, the first time I open the MATE menu, nothing will happen for several seconds and during that time, MATE will ignore any (left or right) clicks on any window decoration or panel part. Some panel icons are also affected (like the volume one), but the Quicklaunch icons remain responsive, including the hide windows/show desktop button. Keyboard shortcuts like Alt-F2 and Ctrl-Shift-T still work.

It does not seem to matter how long the MATE session has been running. If the menu was opened sometime during that session, it will from then on work fine. If it hasn't been opened yet (or it is being/was changed by a new install, if I'm not mistaken), it will invariably freeze anything panel and window manager related for some seconds.

Not sure this belongs here, since it affects parts outside of the menu, but I figured I wouldn't know where else to put it.

**Comment by NiceandGently** [comment]
Is the issue still exists with released debian Jessie?

**Comment by 20100922-github** [comment]
Any (research) progress on this one? I can confirm this kind of lag when opening the MATE menu ("Advanced MATE menu") for the first time (either after (re)boot or after (re)login): On my newly Dell XPS 13 that's a 2-3 seconds delay which is a bit annoying for this kind of modern notebook. Cannot confirm any icon issues though. Running Ubuntu Linux 14.04 LTS here with MATE desktop 1.8.2. Other available menus ("Gnome main menu", "main menu", "menu bar") do not have this lag.

**Comment by flexiondotorg** [comment]
If you are referring to mintMenu (from Linux Mint MATE or LMDE) or MATE Menu (derived from mintMenu) and used in Ubuntu MATE, then these menus are not part of MATE or mate-menus. 

They are 3rd party add-ons from the other projects. @AndyProk, what menu were you referring too?

**Comment by 20100922-github** [comment]
@flexiondotorg, if that helps from my side:

I installed MATE according to https://wiki.ubuntuusers.de/MATE#Ubuntu-14-04 on my plain Ubuntu 14.04 - i.e. added the PPA ubuntu-mate-dev/trusty-mate. "dpkg -l | grep mate" tells me that "mate-menu" (which is, I guess the menu, I am talking about - description talks about "Advanced MATE menu") is version 5.6.5a-0ubuntu1~trusty1.

**Comment by NiceandGently** [comment]
mint-menu or MATE Menu use python which is a bit slower, but 2-3 seconds is much time.

**Comment by flexiondotorg** [comment]
This bug is not in mate-menus, not is it on a core MATE component. The bug below is the one you want to progress :-)

  * https://github.com/linuxmint/mintmenu/issues/56
