### ISSUE TITLE
Unable to click lower entries in long submenus

### ISSUE THREAD

**Issue by AndyProk** [mate-desktop/mate-menus#23]
When a submenu has enough entries that the screen height isn't enough, a handy little arrow appears on the bottom of the submenu so that you may hover your mouse over it to scroll down and see the lower, off-screen entries.

The problem is, if you scroll down that way and then try to click on one of those lower entries, the menu instantly scrolls back up the moment your mouse leaver the area of the arrow, making it impossible to click on those entries. An example would be the system settings submenu on a laptop.

For some submenus I solved it by using mozo to put those entries in subsubmenus, but that only circumvents the issue and doesn't remove it.

Dist: debian jessie x86_64
mate-menu 1.8.0-5

**Comment by dabreese00** [comment]
I can confirm this in Slackware64 -current, MATE version 1.10, Dell Studio XPS 1640 using trackpad.  For me anyway, it's intermittent.  It happens not too often, and I can fix it usually by random fidgets such as switching virtual desktops.  But the symptoms are exactly as described by AndyProk.

Steps to reproduce:
1. Open "Applications" menu in mate-panel.
2. Open a submenu that's too long for the screen, so it has "arrow scrollers" at top and bottom.
3. Hover mouse over the bottom "arrow scroller" to scroll down to the bottom of the submenu.
4. Move mouse up, to try to click on the last (bottom) menu item, just above the "arrow scroller".

Expected results: The menu stays scrolled all the way down to the bottom, so the mouse is now hovering over the bottom menu item, and can click on it.

Actual results: As soon as the mouse moves above the bottom "arrow scroller", the menu scrolls immediately back up to the top, leaving the mouse hovering over the wrong item.  So it's impossible to click on the item(s) at the bottom of the menu.

Note: I've noticed that, at least some of the time, the above symptom seems to come and go precisely alongside another symptom: I can't click and drag a scroll bar in application windows in MATE, for example dconf editor.  The scroll bar just get stuck in place when I try to drag it.  Scrolling in any other normal way works fine, I just can't drag the bar anywhere.  This might point to an issue broader than just mate-menus?

Any logs I should provide, if I notice this again?

**Comment by archnous** [comment]
Same here, Archlinux/Mate since 1.10. 1.12 also has this problem, however 1.8 was OK. Can't select the lowest items in taller-than-screen-height submenus of the "main Mate menu", as the list snaps back to top as soon as the mouse pointer leaves the submenu's down-arrow or the mouse wheel stops scrolling the list up.

![mate-menu-snap](https://cloud.githubusercontent.com/assets/6310912/11011525/8a269908-84f1-11e5-9833-51893bc0913a.gif)

**Comment by tele1** [comment]
Confirmed on my PCLinuxS Mate 64 bit
http://www.pclinuxos.com/forum/index.php/topic,135415.0.html
http://www.youtube.com/watch?v=nD8GpXotKcQ

**Comment by flexiondotorg** [comment]
This is the wrong project for this issue. If this issue is still present please file it again in:

  * https://github.com/mate-desktop/mate-panel

**Comment by tele1** [comment]
Looks fixed when Mate was port to gtk3.
