### ISSUE TITLE
Mate application menu is empty

### ISSUE THREAD

**Issue by alacerda** [mate-desktop/mate-menus#26]
Hi,

I've just installed mate-menus and my task bar shows "System" and "Places" menus but despite "Application" menu being showed it is empty - there is no submenus (directories) in it.

**Comment by NiceandGently** [comment]
distro? version?

**Comment by alacerda** [comment]
Alpine Linux 3.1.2
Packages installed: http://hastebin.com/bolorehiru.hs

**Comment by NiceandGently** [comment]
@alacerda 
Please close it
