### ISSUE TITLE
xdg-open does not use engrampa for .zip files

### ISSUE THREAD

**Issue by cweiske** [mate-desktop/mate-menus#28]
When doing `xdg-open file.zip`, the contents of the file are displayed with `less` in a terminal - instead of using `engrampa`.

`xdg-open` tries to find the application by looking into the following files:
- `~/.local/share/applications/mimeapps.list`
- `/usr/share/mate/applications/defaults.list`
- `/usr/share/applications/defaults.list`

`/usr/share/mate/applications/defaults.list` does not exist, so it falls back to the default file provided by the ubuntu 14.04 `desktop-file-utils` package. This one maps .zip files to file-roller:

```
application/zip=file-roller.desktop
```

It would help if mate shipped its own `defaults.list` file that actually defines engrampa to be used for zip files.
##

**Comment by Lantizia** [comment]
I second this, exceptionally annoying.

**Comment by flexiondotorg** [comment]
This is a distro maintainer issue. I've tested this in Ubuntu MATE 17.04 alpha and Ubuntu MATE 16.04 and `xdg-open file.zip` opens in Engrampa.
