### ISSUE TITLE
Same icons appear twice since upgrading from Linux Mint Mate 17.1 to 17.2

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-menus#31]
In the menu System - Administration, some icons appears twice after upgrading from Linux Mint Mate 17.1 to 17.2.
![capture-menu principal](https://cloud.githubusercontent.com/assets/3955499/8606675/8b42c3a6-268d-11e5-9b62-5179890485cc.png)

**Comment by monsta** [comment]
This is not mate-menus bug in any way. Remove old ```mate-system-tools``` package which is not auto-removed on upgrade.

@infirit: please close this

**Comment by Petrouchka** [comment]
I removed mate-system-tools and mate-system-tools-common, the problem il always the same :

![capture-menu principal](https://cloud.githubusercontent.com/assets/3955499/8721296/c45308dc-2bb9-11e5-8e0d-b4ab252bbc63.png)

**Comment by monsta** [comment]
Remove the modified ```.desktop``` files from ```~/.local/share/applications/``` as well.

**Comment by Petrouchka** [comment]
I removed the ~/.local/share/applications/ folder and it remins any double icons :

![capture-menu principal](https://cloud.githubusercontent.com/assets/3955499/8721640/a3438948-2bbc-11e5-8a0c-878958c3001a.png)

**Comment by Petrouchka** [comment]
The bug is not completely resolved and you close it ???

**Comment by monsta** [comment]
It's resolved. The remaining duplicates (Software Manager and Backup Tool) are **not** related to this issue.

They've been in Mint releases for ages.
They're here because these apps contain duplicate executable files (```mintinstall/mintInstall``` and ```mintbackup/mintBackup```).
These duplicates are hidden by default so you won't see them in mintMenu.

**Comment by Petrouchka** [comment]
Ok, thank you for your quick and efficient help.
I installed a lot of Linux Mint on my friends, family and customers computers for 2 years. Do you think it's possible to have an automatic update to do what you explained ?

**Comment by monsta** [comment]
It's better to ask @clefebvre about any possible updates.

**Comment by Petrouchka** [comment]
Thank you, I will look how to contact him.

**Comment by monsta** [comment]
The quickest way is via IRC (```irc.spotchat.org```, ```#linuxmint-dev``` channel). Launch Hexchat and join that channel. If you're lucky Clem will be online :smile:

**Comment by Petrouchka** [comment]
Thank you very much, I will try until I can join him.
I noticed another double icon :

![capture](https://cloud.githubusercontent.com/assets/3955499/8722276/08cbe688-2bc3-11e5-9174-b3a5bb19a7ed.png)

**Comment by monsta** [comment]
That's ```mate-calc``` (old, from 1.8) and ```gcalctool``` (new replacement, installed on upgrade). Remove the one you don't like.

**Comment by Petrouchka** [comment]
I removed mate-calc and mate-calc-commons packages, it's OK now.

**Comment by Petrouchka** [comment]
In the menu System - Administration, some icons appears twice in Linux Mint Mate 18 :
![screenshot at 2016-07-01 22 56 25](https://cloud.githubusercontent.com/assets/3955499/16534560/f2cdf4ec-3fe0-11e6-8755-1a830dcd5508.png)
