### ISSUE TITLE
Menus are in double

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-menus#34]
Some menus are twice.
![capture](https://cloud.githubusercontent.com/assets/3955499/11324834/e7118332-913d-11e5-8fa8-43cc5f497fff.png)

**Comment by raveit65** [comment]
I don't see that in fedora.
Did you file out a report at Linuxmint?

**Comment by Petrouchka** [comment]
No, I'm lost between MATE, Mint and other Git issues.

**Comment by Petrouchka** [comment]
Done : https://github.com/linuxmint/mintmenu/issues/144

**Comment by monsta** [comment]
Oh come on... I thought we already sorted it out in https://github.com/mate-desktop/mate-menus/issues/31?

**Comment by Petrouchka** [comment]
No, I made a fresh install with Linux Mint MATE 17.3 bêta.

**Comment by monsta** [comment]
Please read my comment about duplicate executable files at https://github.com/mate-desktop/mate-menus/issues/31#issuecomment-121930421 once more...

**Comment by Petrouchka** [comment]
Yes, I read it. But even all the menus are hidden (not checked), it would be better to have them once. It would be more clear. When somebody want to modify menus, he can't understand what are all these menus in two or three times.

**Comment by Petrouchka** [comment]
Closed ????
