### ISSUE TITLE
New level in menus is not convenient

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-menus#35]
A new level is added in the System - Preferences menu. It isn't convenient, it's more difficult now to find a software in these 3 levels. Please let the menu with only 2 levels, as it was before :
![paramtrage_mate-16](https://cloud.githubusercontent.com/assets/3955499/11419653/1eff4cdc-9429-11e5-9d82-6e2c383304ee.png)

**Comment by raveit65** [comment]
Well, there is a discussion about, see https://github.com/mate-desktop/mate-control-center/issues/207#issue-116918221
This will be improved for 1.14.
For the moment you file out a report against your distro and ask maintainer to make /etc/xdg/menus/mate-preferences-categories.menu optional with a package split.
A quick and dirty solution is to delete this file.

**Comment by Petrouchka** [comment]
Done : https://github.com/linuxmint/mate/issues/6

**Comment by monsta** [comment]
I didn't realize that first, but it's actually technically possible to override settings from ```/etc/xdg/menus``` via settings in ```~/.config/menus``` dir. I hope to figure out how to do it, so I'll leave this issue open for a while. It would be even more flexible than making a separate package: the settings can be overridden for each user in the system.

**Comment by Petrouchka** [comment]
Always 3 levels in the System - Preferences menu in Linux Mint MATE 18.

**Comment by raveit65** [comment]
That linuxmint do not a package split for easy uninstall of preferences menus isn't our problem.
File out a report there.

**Comment by dareksmok** [comment]
https://www.dropbox.com/s/jv22k5ye39cmfyg/mate%20menu.png?dl=0

With reference to the menu Mate, proposes to add a new item (3), in the setting panel.

I mean, about the integration of the panel and the menu in terms of theme, where after you select the appropriate position (Mate menu) will be their integration (synchronization):

kolor panel = kolor menu

transparency transparency = panel menu
https://www.dropbox.com/s/jv22k5ye39cmfyg/mate%20menu.png?dl=0
http://manjaro.pl/wp-content/uploads/2016/03/VirtualBox_NetRunner_01_03_2016_10_54_32.jpg

=========================================

W nawiązaniu do menu Mate, proponuje dodanie nowej pozycji (3) ,  w ustawieniu panelu.

Chodzi mi, o integracje panelu i menu w zakresie motywu, gdzie po zaznaczeniu odpowiedniej pozycji w ( Mate menu) nastąpi ich integracja (synchronizacja):

kolor panel = kolor menu

przezroczystość panelu =  przezroczystość menu
