### ISSUE TITLE
mate-preferences-categories.menu left out of last commit

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-menus#36]
https://github.com/mate-desktop/mate-menus/commit/4a05f1d22ae547d1a2cf555f5ecddcf583683751

did not actually add the menu file. Gives  build error 

make[2]: *** No rule to make target 'mate-preferences-categories.menu', needed by 'all-am'.  Stop.

Copying the file in from an older mate-control-center source tarball fixes the build and the resulting package works

**Comment by raveit65** [comment]
opps, the file itself is missing
Thanks, fixed
https://github.com/mate-desktop/mate-menus/commit/2cf6bf0d7846411ea54b534d6ea7039a93d7d1d2
