### ISSUE TITLE
slow first open menu

### ISSUE THREAD

**Issue by tele1** [mate-desktop/mate-menus#37]
When I run Mate, I can from Desktop open for example or from task-bar Firefox and working,
when I open mate-menu I need about 2 seconds, and all mate stooped, 
I can not for example in this 2 seconds minimalize Firefox window.

Is this possible improve mate-menu ?
- Lower status validity ( I want do something other in this 2 seconds :-) )
- Increase speed,
   I have almost new computer , 2 seconds load this is a lot,

Intel Core i5-3470 BOX
MSI Z77A-G43
Gigabyte GTX 660 WF2 = 2GB GDDR5 192-bit
2x 4GB Kingston HyperX 1600 MHz

If this is possible I suggest rebuild or build to new Mate-Menu,
 or port other source code GNU GPL menu and add more options to debug.

mate-mint-menu 5.6.2
mate-menus 1.12.0
System: PCLinuxOS 64 bit.
Mate: 1.12.1

it seems to me that once (a long time ago) worked faster, but I might be wrong.

**Comment by monsta** [comment]
This is a library, not a menu applet. Please report at https://bitbucket.org/ubuntu-mate/mate-menu or https://github.com/linuxmint/mintmenu (I have no idea which one is packaged in your distro).
