### ISSUE TITLE
Drop python2 support

### ISSUE THREAD

**Issue by ghostplant** [mate-desktop/mate-menus#39]
Is it possible to drop python2 support and migrate dependencies to python3

**Comment by monsta** [comment]
Well, @XRevan86 will probably explain it better than me... but I think someday we'll do this as python2 is being gradually deprecated or even removed from some distros. We need to drop old-style python bindings and fix introspection bindings here first.

**Comment by XRevan86** [comment]
It is more preferrable to go for GObject Introspection bindings and not rely on python-dependant bindings. But work in this area is not done yet.
