### ISSUE TITLE
Unfold on hover for Mate menu

### ISSUE THREAD

**Issue by damascene** [mate-desktop/mate-menus#40]
It would be a cool feature if Mate menu/top left menu/Main menu would unfold on hover. It would give similar feeling to the Gnome Shell mouse on corner. it would be easier to run application and type it's names.

so could you please add unfold on hover for those menus?
##

**Comment by damascene** [comment]
There is a simple solution by modifying the file: 
`/usr/lib/mate-menu/mate-menu.py`
Here are the complete instructions
http://askubuntu.com/questions/791452/how-to-unfold-mate-menu-on-hover-hot-corner/791457#791457

**Comment by flexiondotorg** [comment]
This is not the right project to raise this issue. Please can you file this at:

  * https://bitbucket.com/ubuntu-mate/mate-menu
