### ISSUE TITLE
An icon appears twice

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-menus#41]
In the menu System - Administration, an icon appears twice in Linux Mint Mate 18 :
![screenshot at 2016-07-01 22 56 25](https://cloud.githubusercontent.com/assets/3955499/16534599/4397670a-3fe1-11e6-807f-0c8af4e3b7aa.png)

**Comment by Petrouchka** [comment]
This issue has been solved ?

**Comment by monsta** [comment]
No, you just posted Mint-specific issue in the wrong place once again. We already discussed everything at https://github.com/mate-desktop/mate-menus/issues/31.

**Comment by Petrouchka** [comment]
Thank you. I will report it to Linux Mint.
