### ISSUE TITLE
The integration of the theme of the panel and menu.

### ISSUE THREAD

**Issue by dareksmok** [mate-desktop/mate-menus#43]
![mate menu](https://cloud.githubusercontent.com/assets/13463344/17275944/c57c1e7e-5719-11e6-8dde-a244f4dd8c00.png)

With reference to the menu Mate, proposes to add a new item (3), in the setting panel.

I mean, about the integration of the panel and the menu in terms of theme, where after you select the appropriate position (Mate menu) will be their integration (synchronization):

kolor panel = kolor menu

transparency panel  = transparency  menu

![transparency menu](https://cloud.githubusercontent.com/assets/13463344/17275962/5a5635e8-571a-11e6-891d-7343487232ae.jpg)
# 

W nawiązaniu do menu Mate, proponuje dodanie nowej pozycji (3) , w ustawieniu panelu.

Chodzi mi, o integracje panelu i menu w zakresie motywu, gdzie po zaznaczeniu odpowiedniej pozycji w ( Mate menu) nastąpi ich integracja (synchronizacja):

kolor panel = kolor menu

przezroczystość panelu = przezroczystość menu
##

**Comment by dareksmok** [comment]
Beautifying the system - GNOME 2 & MATE http://forum.rosalab.ru/en/viewtopic.php?f=34&t=2494

**Comment by flexiondotorg** [comment]
This is not to correct project for this issue. Please can you file this issue in:

  * https://github.com/mate-desktop/mate-panel
