### ISSUE TITLE
Read-Only menu items?

### ISSUE THREAD

**Issue by asdf23** [mate-desktop/mate-menus#45]
How can I edit other items in the menu specifically items under Places or System.

**Comment by raveit65** [comment]
You can't edit them, they are defined in text files under /etc/xdg/menus/

**Comment by raveit65** [comment]
Btw. github is for bugreporting and not for questions about Mate works.
If everybody ask questions here we don't have the time to fix bugs any more.
We are a small team.

**Comment by asdf23** [comment]
Sorry just from my perspective mozo seems incomplete.
