### ISSUE TITLE
Customization Question

### ISSUE THREAD

**Issue by Shark-Linux** [mate-desktop/mate-menus#47]
Was hoping you may be able to offer me some advice the best way to implement some hackery and change the titles on the advanced menu (in 1.16 and *.18) Im able to add categories and custom launchers, however Im caught up on the titles to sections provided by plugins. To eliminate possibility of confusion,  Ive attached a screen shot and boxed in red the tags im referencing.
![untitled](https://cloud.githubusercontent.com/assets/23142357/25336668/8dc862e2-28c6-11e7-8834-5631ec43de9e.png)

**Comment by Shark-Linux** [comment]
Ive figured it out on my own. No further questions

**Comment by monsta** [comment]
This menu is hosted at https://bitbucket.org/ubuntu-mate/mate-menu/
