### ISSUE TITLE
"Edit menu" does not trigger Mozo

### ISSUE THREAD

**Issue by Kallestofeles** [mate-desktop/mate-menus#49]
Hello,

When right-clicking on mate-menu and selecting "Edit menu", then Mozo is not triggered. Nothing happens.
Mozo by itself can be opened up just fine without errors.

Please let me know if and how can I provide any needed logs for this as I am not sure about getting logs for panel items.

Arch Linux
64bit
MATE 1.18.0

**Comment by epgfm** [comment]
Downstream bug report for Ubuntu MATE 17.04:

https://bugs.launchpad.net/ubuntu-mate/+bug/1692104

I'm not sure this is a mate-menus problem or a mate-applets problem.
@monsta ?

**Comment by monsta** [comment]
It's reproducible with classic menus as well, so I've added a report at https://github.com/mate-desktop/mate-panel/issues/586.
For the advanced menu, you should report at https://bitbucket.org/ubuntu-mate/mate-menu.
