### ISSUE TITLE
I cannot compile mate-menus with GCC 7.1.0 on Cross Linux from Scratch 20170702 x86_64 multilib (64-bit version)

### ISSUE THREAD

**Issue by overflyer87** [mate-desktop/mate-menus#52]
#### Expected behaviour
python/matemenu.c gets compiled properly by make command

#### Actual behaviour
Several compile ERRORS are thrown 

#### Steps to reproduce the behaviour
configure log https://hastebin.com/abapiyuwis.makefile  
make install log https://hastebin.com/nepojefujo.swift
configured with
LIBSOUP_LIBS=/usr/lib64 \
  ACLOCAL_FLAG=/usr/share/aclocal/ CC="gcc ${BUILD64}" \
  CXX="g++ ${BUILD64}" USE_ARCH=64 \
   PKG_CONFIG_PATH=${PKG_CONFIG_PATH64} sh autogen.sh --prefix=/usr \
   --libdir=/usr/lib64 --sysconfdir=/etc --disable-static \
   --localstatedir=/var --bindir=/usr/bin --sbindir=/usr/sbin \
--datadir=/usr/share/doc 

make command is:

USE_ARCH=64 CC="gcc ${BUILD64}" CXX="g++ ${BUILD64}" PKG_CONFIG_PATH="${PKG_CONFIG_PATH64}" make LIBDIR=/usr/lib64 PREFIX=/usr

Obvious workaround that fixes this is passing --disable-python, but of course I dont want that to be my permanent solution

#### MATE general version
1.18.0

#### Package version
1.18.0

#### Linux Distribution
 Cross Linux from Scratch 20170702 x86_64 multilib

**Comment by overflyer87** [comment]
Is the explanation maybe that I am using Python 3.6 on my system ONLY? Does mate-menu need 2.7?  Then on the other hand that would probably not explain compile errors in C code.

**Comment by overflyer87** [comment]
Installation of Python 2.7.13 with multilib patch from gentoo fixed it for me. Would be nice to now if you guys plan to support Python 3.6 or even have a patch for that.

**Comment by monsta** [comment]
Yes, it's for Python 2.
Someday we'll drop these legacy bindings and add GObject introspection support, like it's already done in other projects.
