### ISSUE TITLE
menu click fail

### ISSUE THREAD

**Issue by gitumor** [mate-desktop/mate-menus#56]
#### Expected behaviour
An application would launch when a menu item is clicked.

#### Actual behaviour
Nothing happens when clicking any item in the menu.

#### Steps to reproduce the behaviour
Open the menu and click on an item.

#### MATE general version
MATE 1.18.0

#### Package version
mate-menu.py 17.10.6

#### Linux Distribution
openSUSE Leap 42.3

**Comment by raveit65** [comment]
I can't reproduce this with fedora.
This needs to be reproduced by open-suse maintainer, for this reason we ask for a downstream bugreport.
@XRevan86

**Comment by monsta** [comment]
This isn't our issue anyway.

https://github.com/ubuntu-mate/mate-menu
