### ISSUE TITLE
Menus won't close with a single click over their buttons when they're open

### ISSUE THREAD

**Issue by o-alquimista** [mate-desktop/mate-menus#57]
#### Expected behaviour
Menus would close with one click over their button, while they're open

#### Actual behaviour
Menus remain open when you click to close. You click again and they finally close. One click opens, two clicks close. The clicks don't have to be within some time frame, you can click once and later click again to successfully close the menu.

#### Steps to reproduce the behaviour
Click on mate-menu to open, move the mouse to other menus, in and out... then try to close them by clicking on top of any menu button.

#### MATE general version
1.18.0

#### Package version
1.18.0-0ubuntu1

#### Linux Distribution
Ubuntu MATE 17.04

#### Link to downstream report of your Distribution
none (affects other distributions too, from Debian 9 to Arch Linux).

**Comment by monsta** [comment]
https://github.com/ubuntu-mate/mate-menu
