### ISSUE TITLE
Cheese icon is twice in MATE menu

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-menus#58]
#### Expected behaviour
Cheese icon should be once in MATE menu (Applications - Sound and video)

#### Actual behaviour
Cheese icon is twice in MATE menu (Applications - Sound and video)

#### Steps to reproduce the behaviour
Install Cheese.
In directory ~/.local/share/applications/, there are 2 menu configuration files : org.gnome.Cheese.desktop and cheese.destop. Perhaps one should be deleted but which ?

```
$ diff org.gnome.Cheese.desktop cheese.desktop 
17d16
< DBusActivatable=true
19c18
< NoDisplay=true
---
> X-AppStream-Ignore=true
```

#### MATE general version
1.18.0

#### Linux Distribution
Linux Mint 18.2,updated from 18.1, updated from 18.0

**Comment by monsta** [comment]
Not related to MATE, both files are shipped in cheese package
