### ISSUE TITLE
Icons not appearing in some locales due to erronous translation

### ISSUE THREAD

**Issue by lah7** [mate-desktop/mate-menus#81]
#### Expected behaviour

Icons to appear in the MATE menu for non-English locales.

#### Actual behaviour

Category icons appear with a clashed circle. 

![image](https://user-images.githubusercontent.com/13032135/80796763-f54ce000-8b97-11ea-9e6c-7041510442bf.png)

The `Icon` field in some locales is incorrectly translated and included in the resulting `.mo` file in `/usr/share/locale`, for example:

https://github.com/mate-desktop/mate-menus/blob/a804a6ad51f10bce233351efd7f33d5bad480a1d/po/pt.po#L80-L82

 I suggest the `Icon` field is excluded from POT/PO files (or stripped at build time) to avoid future erroneous translations. This might also be worthwhile automating into other MATE applications, which currently state:

```
#. Translators: Do NOT translate or transliterate this text
```

to avoid a similar issue where a few other MATE applications have missing icons.

#### Steps to reproduce the behaviour

* Switch to a problematic locale, such as `pt-br` and `pt`.

#### MATE general version

1.24.0

#### Package version

* mate-menus-1.24.0-1

#### Linux Distribution

* Ubuntu MATE 20.04

#### Link to downstream report of your Distribution

https://bugs.launchpad.net/ubuntu-mate/+bug/1873466

**Comment by raveit65** [comment]
Take  a look at repos. There are commits which fixes the problem. You or Martin need to add those commits as patches directly to your ubuntu installer packages.
Search for `Do not collect the translation for Icon` in git history of several packages. Eg.
https://github.com/mate-desktop/mate-menus/commit/39c11887c2fc8098eff2fa77163f85b90df6212a
Translators are humans and humans makes mistakes.....

But i am still still wondering that all guys from upstream MATE team at UbuntuMate Slack channel are not informed!
We all received regular mail notifications in February/March about this problem.....

**Comment by lah7** [comment]
My apologies, I was searching specifically at the PO files, which wasn't been updated since 24 Jan.

I'm not involved in packaging from Ubuntu MATE, but I will let @flexiondotorg know what he needs to do...

**Comment by raveit65** [comment]
....thanks for importing information....
