### ISSUE TITLE
"Problem, mate-menu 20xxx requires python3xxxx, but it isn't available???"

### ISSUE THREAD

**Issue by esteelpaz** [mate-desktop/mate-menus#87]
#### Actual behaviour:  running "zypper dup -l" provides error:  ```
Problem: mate-menu-20.04.1-2.1.noarch requires python3-xdg, but this requirement cannot be provided
  deleted providers: python3-pyxdg-0.26-6.2.noarch
not installable providers: python3-xdg-4.0.1-1.1.noarch[download.opensuse.org-oss]
 Solution 1: Following actions will be done:
  deinstallation of mate-menu-20.04.1-2.1.noarch
  deinstallation of mate-panel-branding-openSUSE-42.1-4.44.noarch
  deinstallation of mate-menu-lang-20.04.1-2.1.noarch
 Solution 2: deinstallation of python3-pyxdg-0.26-6.2.noarch
 Solution 3: keep obsolete python3-pyxdg-0.26-6.2.noarch
 Solution 4: break mate-menu-20.04.1-2.1.noarch by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/4/c/d/?] (c):
```
In Sys76 laptop resulting choice of options left the log in window showing as a black screen . . . if password is entered in the black then system will log into regular GUI.  Problem went away when selecting earlier 5.8 kernel option.

#### Steps to reproduce the behaviour:  command has been run in two machines on two distros of TW.


#### MATE general version??


#### Package version??


#### Linux Distribution OpenSUSE TW & Gecko TW.


#### Link to downstream report of your Distribution

**Comment by lukefromdc** [comment]
This is a packaging issu with your distro, not an upstream issue. You need to file issues with OpenSUSE TW & Gecko TW instead, as only they can fix this. Looks like they have python updates out of synch with their build of mate-menus and need to rebuild that package from the same source

**Comment by esteelpaz** [comment]
@lukefromdc :+1: 

A gent on bugzilla posted to a bug report filed there by someone else having this issue:

> Actually, I believe only mate-menu depends on python3-pyxdg.  When I test this by telling zypper to remove python3-pyxdg, I see this:

> sudo zypper remove python3-pyxdg
Reading installed packages...
Resolving package dependencies...

The following 3 packages are going to be REMOVED:
  mate-menu mate-menu-lang python3-pyxdg

3 packages to remove.
After the operation, 1.3 MiB will be freed.
Continue? [y/n/v/...? shows all options] (y): n

So please rebuild mate-menu and mate-menu-lang against the new python3-pyxdg.

Thanks,
Gene
