### ISSUE TITLE
Crash when adding mint-menu to Panel after upgrade to Mint 20

### ISSUE THREAD

**Issue by protoman** [mate-desktop/mate-menus#89]
#### Expected behaviour
The applet for the mint-menu is added and works.

#### Actual behaviour
Crashes with this on syslog:
Nov 19 10:29:31 Doctor org.mate.panel.applet.MintMenuAppletFactory[6644]: #015Building dependency tree... 0%#015#015Building dependency tree... 0%#015#015Building dependency tree... 50%#015#015Building dependency tree... 50%#015#015Building dependency tree
Nov 19 10:29:31 Doctor org.mate.panel.applet.MintMenuAppletFactory[6644]: #015Reading state information... 0%#015#015Reading state information... 0%#015#015Reading state information... Done
Nov 19 10:29:33 Doctor kernel: [ 6062.756204] mintmenu[6633]: segfault at 4 ip 00007f59f20d2d04 sp 00007ffcda791ef8 error 4 in libgtk-3.so.0.2404.16[7f59f1f2d000+36f000]
Nov 19 10:29:33 Doctor kernel: [ 6062.756211] Code: 84 00 00 00 00 00 45 31 e4 48 83 c4 08 4c 89 e0 5d 41 5c c3 66 90 f3 0f 1e fa 83 47 04 01 48 89 f8 c3 0f 1f 40 00 f3 0f 1e fa <8b> 47 04 83 e8 01 89 47 04 85 c0 7f 37 55 83 3f 07 48 89 fd 77 69
Nov 19 10:29:33 Doctor systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Nov 19 10:29:33 Doctor systemd[1]: Started Process Core Dump (PID 6652/UID 0).
Nov 19 10:29:38 Doctor systemd-coredump[6653]: Process 6633 (mintmenu) of user 1000 dumped core.#012#012Stack trace of thread 6633:#012#0  0x00007f59f20d2d04 n/a (libgtk-3.so.0 + 0x22ad04)#012#1  0x00007f59f205babf n/a (libgtk-3.so.0 + 0x1b3abf)#012#2  0x00007f59f3a25487 g_datalist_clear (libglib-2.0.so.0 + 0x32487)#012#3  0x00007f59f39acd0e g_object_unref (libgobject-2.0.so.0 + 0x19d0e)#012#4  0x00007f59f3b89e8a n/a (_gi.cpython-38-x86_64-linux-gnu.so + 0x35e8a)#012#5  0x00000000005a74dc n/a (python3.8 + 0x1a74dc)#012#6  0x00000000005cd423 n/a (python3.8 + 0x1cd423)#012#7  0x00000000005d304c n/a (python3.8 + 0x1d304c)#012#8  0x00000000005eca2b n/a (python3.8 + 0x1eca2b)#012#9  0x00000000005ecee8 n/a (python3.8 + 0x1ecee8)#012#10 0x00000000005f717d _PyFunction_Vectorcall (python3.8 + 0x1f717d)#012#11 0x000000000056b399 _PyEval_EvalFrameDefault (python3.8 + 0x16b399)#012#12 0x00000000005f7146 _PyFunction_Vectorcall (python3.8 + 0x1f7146)#012#13 0x000000000056b399 _PyEval_EvalFrameDefault (python3.8 + 0x16b399)#012#14 0x000000000056955a _PyEval_EvalCodeWithName (python3.8 + 0x16955a)#012#15 0x00000000005f7323 _PyFunction_Vectorcall (python3.8 + 0x1f7323)#012#16 0x000000000056b399 _PyEval_EvalFrameDefault (python3.8 + 0x16b399)#012#17 0x00000000005f7146 _PyFunction_Vectorcall (python3.8 + 0x1f7146)#012#18 0x000000000056b399 _PyEval_EvalFrameDefault (python3.8 + 0x16b399)#012#19 0x00000000005f7146 _PyFunction_Vectorcall (python3.8 + 0x1f7146)#012#20 0x000000000056b399 _PyEval_EvalFrameDefault (python3.8 + 0x16b399)#012#21 0x00000000005f7146 _PyFunction_Vectorcall (python3.8 + 0x1f7146)#012#22 0x000000000059c95d n/a (python3.8 + 0x19c95d)#012#23 0x00000000005f463f _PyObject_MakeTpCall (python3.8 + 0x1f463f)#012#24 0x00000000005704b9 _PyEval_EvalFrameDefault (python3.8 + 0x1704b9)#012#25 0x000000000056955a _PyEval_EvalCodeWithName (python3.8 + 0x16955a)#012#26 0x00000000005f7323 _PyFunction_Vectorcall (python3.8 + 0x1f7323)#012#27 0x000000000059c95d n/a (python3.8 + 0x19c95d)#012#28 0x00000000005f463f _PyObject_MakeTpCall (python3.8 + 0x1f463f)#012#29 0x00000000005704b9 _PyEval_EvalFrameDefault (python3.8 + 0x1704b9)#012#30 0x00000000005f7146 _PyFunction_Vectorcall (python3.8 + 0x1f7146)#012#31 0x00000000005f6e27 PyObject_CallObject (python3.8 + 0x1f6e27)#012#32 0x00007f59f3b74e4e n/a (_gi.cpython-38-x86_64-linux-gnu.so + 0x20e4e)#012#33 0x00007f59f4846e06 n/a (libffi.so.7 + 0x6e06)#012#34 0x00007f59f4847188 n/a (libffi.so.7 + 0x7188)#012#35 0x00007f59f1aa003b mate_panel_applet_marshal_BOOLEAN__STRING (libmate-panel-applet-4.so.1 + 0x803b)#012#36 0x00007f59f39a7802 g_closure_invoke (libgobject-2.0.so.0 + 0x14802)#012#37 0x00007f59f1aa0909 n/a (libmate-panel-applet-4.so.1 + 0x8909)#012#38 0x00007f59f39a7a56 n/a (libgobject-2.0.so.0 + 0x14a56)#012#39 0x00007f59f39c6b28 g_signal_emit_valist (libgobject-2.0.so.0 + 0x33b28)#012#40 0x00007f59f39c7b7c g_signal_emit_by_name (libgobject-2.0.so.0 + 0x34b7c)#012#41 0x00007f59f2281e57 n/a (libgtk-3.so.0 + 0x3d9e57)#012#42 0x00007f59f292505f n/a (libgdk-3.so.0 + 0x7005f)#012#43 0x00007f59f29253ac n/a (libgdk-3.so.0 + 0x703ac)#012#44 0x00007f59f28ed0f4 gdk_display_get_event (libgdk-3.so.0 + 0x380f4)#012#45 0x00007f59f29250f6 n/a (libgdk-3.so.0 + 0x700f6)#012#46 0x00007f59f3a44fbd g_main_context_dispatch (libglib-2.0.so.0 + 0x51fbd)#012#47 0x00007f59f3a45240 n/a (libglib-2.0.so.0 + 0x52240)#012#48 0x00007f59f3a45533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)#012#49 0x00007f59f20f637d gtk_main (libgtk-3.so.0 + 0x24e37d)#012#50 0x00007f59f1aa23b8 n/a (libmate-panel-applet-4.so.1 + 0xa3b8)#012#51 0x00007f59f4846ff5 n/a (libffi.so.7 + 0x6ff5)#012#52 0x00007f59f484640a n/a (libffi.so.7 + 0x640a)#012#53 0x00007f59f3b7d0a5 n/a (_gi.cpython-38-x86_64-linux-gnu.so + 0x290a5)#012#54 0x00007f59f3b7425c n/a (_gi.cpython-38-x86_64-linux-gnu.so + 0x2025c)#012#55 0x00000000005f46d6 _PyObject_MakeTpCall (python3.8 + 0x1f46d6)#012#56 0x0000000000570936 _PyEval_EvalFrameDefault (python3.8 + 0x170936)#012#57 0x000000000056955a _PyEval_EvalCodeWithName (python3.8 + 0x16955a)#012#58 0x000000000068c4a7 PyEval_EvalCode (python3.8 + 0x28c4a7)#012#59 0x000000000067bc91 n/a (python3.8 + 0x27bc91)#012#60 0x000000000067bd0f n/a (python3.8 + 0x27bd0f)#012#61 0x000000000067bdcb PyRun_FileExFlags (python3.8 + 0x27bdcb)#012#62 0x000000000067de4e PyRun_SimpleFileExFlags (python3.8 + 0x27de4e)#012#63 0x00000000006b6032 Py_RunMain (python3.8 + 0x2b6032)#012#012Stack trace of thread 6635:#012#0  0x00007f59f473caff __GI___poll (libc.so.6 + 0x115aff)#012#1  0x00007f59f3a451ae n/a (libglib-2.0.so.0 + 0x521ae)#012#2  0x00007f59f3a452e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)#012#3  0x00007f59f3a45331 n/a (libglib-2.0.so.0 + 0x52331)#012#4  0x00007f59f3a6e931 n/a (libglib-2.0.so.0 + 0x7b931)#012#5  0x00007f59f460d609 start_thread (libpthread.so.0 + 0x9609)#012#6  0x00007f59f4749293 __clone (libc.so.6 + 0x122293)#012#012Stack trace of thread 6638:#012#0  0x00007f59f473caff __GI___poll (libc.so.6 + 0x115aff)#012#1  0x00007f59f3a451ae n/a (libglib-2.0.so.0 + 0x521ae)#012#2  0x00007f59f3a452e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)#012#3  0x00007f59f16c699d n/a (libdconfsettings.so + 0xa99d)#012#4  0x00007f59f3a6e931 n/a (libglib-2.0.so.0 + 0x7b931)#012#5  0x00007f59f460d609 start_thread (libpthread.so.0 + 0x9609)#012#6  0x00007f59f4749293 __clone (libc.so.6 + 0x122293)#012#012Stack trace of thread 6636:#012#0  0x00007f59f474289d syscall (libc.so.6 + 0x11b89d)#012#1  0x00007f59f3a925a6 g_cond_wait_until (libglib-2.0.so.0 + 0x9f5a6)#012#2  0x00007f59f3a15561 n/a (libglib-2.0.so.0 + 0x22561)#012#3  0x00007f59f3a15b86 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x22b86)#012#4  0x00007f59f3a6f279 n/a (libglib-2.0.so.0 + 0x7c279)#012#5  0x00007f59f3a6e931 n/a (libglib-2.0.so.0 + 0x7b931)#012#6  0x00007f59f460d609 start_thread (libpthread.so.0 + 0x9609)#012#7  0x00007f59f4749293 __clone (libc.so.6 + 0x122293)#012#012Stack trace of thread 6637:#012#0  0x00007f59f473caff __GI___poll (libc.so.6 + 0x115aff)#012#1  0x00007f59f3a451ae n/a (libglib-2.0.so.0 + 0x521ae)#012#2  0x00007f59f3a45533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)#012#3  0x00007f59f3825eda n/a (libgio-2.0.so.0 + 0x11eeda)#012#4  0x00007f59f3a6e931 n/a (libglib-2.0.so.0 + 0x7b931)#012#5  0x00007f59f460d609 start_thread (libpthread.so.0 + 0x9609)#012#6  0x00007f59f4749293 __clone (libc.so.6 + 0x122293)#012#012Stack trace of thread 6640:#012#0  0x00007f59f473caff __GI___poll (libc.so.6 + 0x115aff)#012#1  0x0000000000636710 n/a (python3.8 + 0x236710)#012#2  0x0000000000504743 n/a (python3.8 + 0x104743)#012#3  0x000000000056b399 _PyEval_EvalFrameDefault (python3.8 + 0x16b399)#012#4  0x000000000056955a _PyEval_EvalCodeWithName (python3.8 + 0x16955a)#012#5  0x00000000005f7323 _PyFunction_Vectorcall (python3.8 + 0x1f7323)#012#6  0x000000000056b399 _PyEval_EvalFrameDefault (python3.8 + 0x16b399)#012#7  0x00000000005f7146 _PyFunction_Vectorcall (python3.8 + 0x1f7146)#012#8  0x000000000056b399 _PyEval_EvalFrameDefault (python3.8 + 0x16b399)#012#9  0x00000000005f7146 _PyFunction_Vectorcall (python3.8 + 0x1f7146)#012#10 0x000000000056b399 _PyEval_EvalFrameDefault (python3.8 + 0x16b399)#012#11 0x00000000005f7146 _PyFunction_Vectorcall (python3.8 + 0x1f7146)#012#12 0x000000000056b399 _PyEval_EvalFrameDefault (python3.8 + 0x16b399)#012#13 0x00000000005f7146 _PyFunction_Vectorcall (python3.8 + 0x1f7146)#012#14 0x000000000050a24c n/a (python3.8 + 0x10a24c)#012#15 0x00000000005f3d42 PyObject_Call (python3.8 + 0x1f3d42)#012#16 0x000000000065561c n/a (python3.8 + 0x25561c)#012#17 0x00000000006750c8 n/a (python3.8 + 0x2750c8)#012#18 0x00007f59f460d609 start_thread (libpthread.so.0 + 0x9609)#012#19 0x00007f59f4749293 __clone (libc.so.6 + 0x122293

#### Steps to reproduce the behaviour
Just try to add the mint-menu applet into the panel.

#### MATE general version
2020.07.09

#### Package version
1.24.0-linuxmint1

#### Linux Distribution
Linux Mint 20

**Comment by raveit65** [comment]
Please quote postings!!!
You have linked a lot of other reports with your numbers in your backtrace.
Thanks for that.
Sorry, mintmenu is third party and developed by linuxmint.
File out a report there.
